name: NASA Project CI
on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        working-directory: ./NASA Project
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build --prefix client
